[package]
name = "simple-scraper"
version = "0.1.0"
authors = ["Malcolm Childs <michilds0@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.1.13", features = ["derive"] }
fantoccini = "0.19.0"
tokio = { version = "1.18.0", features = ["full"] }

