[package]
name = "simple-scraper"
version = "0.1.0"
authors = ["Malcolm Childs <michilds0@gmail.com>"]
edition = "2018"

[dependencies]
fantoccini = "0.11.7"
futures = "0.1"
structopt = "0.2.10"
tokio = "0.1.21"
